language: node_js
node_js: 
  - "stable"  
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER Nuru WITH PASSWORD 'Niyigena1';" -U postgres
script: 
  - npm run test    
after_success:
  - npm run coveralls
  
    