language: node_js
node_js: 
  - "stable"  
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE Teamwork_Testing;" -U postgres 
script: 
  - npm run test    
after_success:
  - npm run coveralls
  
    