language: node_js
node_js: 
  - "stable"  
services:
  - postgresql
before_script:
  - psql -c 'create database Teamwork_Testing;' -U postgres
  - psql -c "create user Nuru WITH PASSWORD 'Niyigena1';" -U postgres
script: 
  - npm run test    
after_success:
  - npm run coveralls
  
    